{% set version = "2.13.2" %}
{% set download_url = "https://github.com/git-lfs/git-lfs/releases/download" %}

package:
  name: git-lfs
  version: {{ version }}

source:
  url: https://github.com/git-lfs/git-lfs/archive/v{{ version }}.tar.gz
  sha256: 782e6275df9ca370730945112e16a0b8c64b9819f0b61fae52ba1ebbc8dce2d5

build:
  number: 0
  skip: True  # [ppc64le]
  # TODO windows support
  skip: True  # [win]
  binary_relocation: False
  detect_binary_files_with_prefix: False

requirements:
  build:
    - {{ compiler('c') }}
    - go

test:
  commands:
    - git-lfs --version
    - git-lfs --help

about:
  home: https://git-lfs.github.com/
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.md'
  summary: An open source Git extension for versioning large files

extra:
  recipe-maintainers:
    - dfroger
    - willirath
