{% set version = "2.13.3" %}
{% set download_url = "https://github.com/git-lfs/git-lfs/releases/download" %}

package:
  name: git-lfs
  version: {{ version }}

source:
  url: {{ download_url }}/v{{ version }}/git-lfs-linux-amd64-v{{ version }}.tar.gz  # [linux]
  sha256: bf6eafb1f9aedbdbfed6bed1b6007400d237a3ab82153908892de6ca7ad902f1  # [linux]

  url: {{ download_url }}/v{{ version }}/git-lfs-darwin-amd64-v{{ version }}.zip  # [osx]
  sha256: bf6eafb1f9aedbdbfed6bed1b6007400d237a3ab82153908892de6ca7ad902f1  # [osx]

  url: {{ download_url }}/v{{ version }}/git-lfs-windows-amd64-v{{ version }}.zip  # [win]
  sha256: bf6eafb1f9aedbdbfed6bed1b6007400d237a3ab82153908892de6ca7ad902f1  # [win]

  url: {{ download_url }}/v{{ version }}/git-lfs-linux-arm64-v{{ version }}.tar.gz  # [aarch64]
  sha256: bf6eafb1f9aedbdbfed6bed1b6007400d237a3ab82153908892de6ca7ad902f1  # [aarch64]

  url: {{ download_url }}/v{{ version }}/git-lfs-linux-ppc64le-v{{ version }}.tar.gz  # [ppc64le]
  sha256: bf6eafb1f9aedbdbfed6bed1b6007400d237a3ab82153908892de6ca7ad902f1  # [ppc64le]

build:
  number: 0
  binary_relocation: false
  detect_binary_files_with_prefix: false

requirements:
  build:
    - git               # [unix]

test:
  commands:
    - codesign -d -vvv $(which git-lfs)             # [osx]
    - shasum -a 256 $(which git-lfs)                # [osx]
    - codesign --verify --verbose $(which git-lfs)  # [osx]
    - git-lfs --help

about:
  home: https://git-lfs.github.com/
  license: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.md
  summary: An open source Git extension for versioning large files

extra:
  recipe-maintainers:
    - dfroger
    - willirath
    - dbast
