{% set name = "git-lfs" %}
{% set version = "3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: ab173702840627feb5f8a408dd5406fa322f3eadaa69938d9226b183d5be25a6

build:
  number: 0
  binary_relocation: false
  detect_binary_files_with_prefix: false
  script:
    - set -euxo pipefail                                                  # [unix]
    # Common flags
    - export GOFLAGS="-buildvcs=false"                                    # [unix]
    # macOS
    - export CGO_ENABLED=0 GOOS=darwin GOARCH=arm64                       # [osx and arm64]
    # Linux
    - export CGO_ENABLED=0 GOOS=linux  GOARCH=arm64                       # [linux and aarch64]
    - export CGO_ENABLED=0 GOOS=linux  GOARCH=amd64                       # [linux and x86_64]
    # Generating and unix build
    - go generate ./commands                                              # [unix]
    - go build -v -ldflags "-w -s" -o "$PREFIX/bin/git-lfs" .             # [unix]
    # Windows
    - go build -v -ldflags "-w -s" -o %PREFIX%\Library\bin\git-lfs.exe .  # [win]
    - mkdir -p license_files && go-licenses save . --save_path=license_files || true  # [unix]
    # Cleanup for Go builds
    - chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)             # [unix]

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses           # [not win]

test:
  commands:
    - test -x $PREFIX/bin/git-lfs                        # [unix]
    - $PREFIX/bin/git-lfs --version                      # [unix]
    - 'IF NOT EXIST "%PREFIX%\\Library\\bin\\git-lfs.exe" EXIT /B 1'  # [win]
    - '"%PREFIX%\\Library\\bin\\git-lfs.exe" --version'               # [win]

about:
  home: https://git-lfs.com
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Git extension for versioning large files
  description: |
    Git LFS is a command line extension and specification for managing large files with Git.
  dev_url: https://github.com/git-lfs/git-lfs
  doc_url: https://github.com/git-lfs/git-lfs/tree/main/docs

extra:
  recipe-maintainers:
    - dfroger
    - willirath
    - dbast
