{% set goname = "github.com/git-lfs/git-lfs" %}
{% set version = "3.6.1" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/", os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  - url: {{ download_url }}/v{{ version }}/git-lfs-linux-s390x-v{{ version }}.tar.gz  # [s390x]
    sha256: c9aa0391ac58c5ed695fceec891c953d12fe78ae31ecbd5fd3cb4204cf8273a9  # [s390x]
  - folder: {{ pkg_src }}  # [not s390x]
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz  # [not s390x]
    sha256: 062603dbef8f221d867e542314e9a6ea1970cae536b4495de2e915529b0fef8e  # [not s390x]


build:
  number: 0
  binary_relocation: false
  detect_binary_files_with_prefix: false
  script:
    - set -x                                                            # [unix and not s390x]
    - cd {{ pkg_src }}                                                  # [not s390x]
    - go mod tidy                                                       # [not s390x]
    - go generate ./commands                                            # [not (osx and arm64) and not s390x]
    - GOARCH=amd64 go generate ./commands                               # [osx and arm64 and not s390x]
    - go build -v -ldflags "-w -s" -o $PREFIX/bin/git-lfs                # [build_platform != target_platform and not s390x]
    - go install -v -ldflags "-w -s" .                                    # [build_platform == target_platform and not win and not s390x]
    - go build -v -ldflags "-w -s" -o %PREFIX%\Library\bin\git-lfs.exe    # [win and not s390x]
    - go-licenses save . --save_path={{ SRC_DIR }}/license_files || true   # [not s390x]
    # Cleanup for Go builds
    - chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)           # [unix and not s390x]
    - ./build_s390x.sh # [s390x]

requirements:
  build:
    - {{ compiler('go') }}  # [not s390x]
    - git
  host:
    - go  # [not s390x]
  run:
    - git
requirements:
  build:
    - {{ compiler('go') }}
    - git
  host:
    - go
  run:
    - git

test:
  commands:
    - shasum -a 256 $(which git-lfs)                # [osx]
    - git-lfs --help

about:
  home: https://git-lfs.com/
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.md
  summary: Git extension for versioning large files
  description: |
    Git LFS is a command line extension and specification for managing large files with Git.
  dev_url: https://github.com/git-lfs/git-lfs
  doc_url: https://github.com/git-lfs/git-lfs/tree/main/docs

extra:
  recipe-maintainers:
    - dfroger
    - willirath
    - dbast
