{% set version = "3.0.1" %}
{% set download_url = "https://github.com/git-lfs/git-lfs/releases/download" %}

package:
  name: git-lfs
  version: {{ version }}

source:
  url: {{ download_url }}/v{{ version }}/git-lfs-linux-amd64-v{{ version }}.tar.gz  # [linux]
  sha256: ebc9847e249d1155a61ca50f28c4bf8df37f76a2262e6cc882dbf4c324f7f1ed  # [linux]

  url: {{ download_url }}/v{{ version }}/git-lfs-darwin-amd64-v{{ version }}.zip  # [osx]
  sha256: ebc9847e249d1155a61ca50f28c4bf8df37f76a2262e6cc882dbf4c324f7f1ed  # [osx]

  url: {{ download_url }}/v{{ version }}/git-lfs-windows-amd64-v{{ version }}.zip  # [win]
  sha256: ebc9847e249d1155a61ca50f28c4bf8df37f76a2262e6cc882dbf4c324f7f1ed  # [win]

  url: {{ download_url }}/v{{ version }}/git-lfs-linux-arm64-v{{ version }}.tar.gz  # [aarch64]
  sha256: ebc9847e249d1155a61ca50f28c4bf8df37f76a2262e6cc882dbf4c324f7f1ed  # [aarch64]

  url: {{ download_url }}/v{{ version }}/git-lfs-linux-ppc64le-v{{ version }}.tar.gz  # [ppc64le]
  sha256: ebc9847e249d1155a61ca50f28c4bf8df37f76a2262e6cc882dbf4c324f7f1ed  # [ppc64le]

build:
  number: 0
  binary_relocation: false
  detect_binary_files_with_prefix: false

requirements:
  build:
    - git               # [unix]

test:
  commands:
    - codesign -d -vvv $(which git-lfs)             # [osx]
    - shasum -a 256 $(which git-lfs)                # [osx]
    - codesign --verify --verbose $(which git-lfs)  # [osx]
    - git-lfs --help

about:
  home: https://git-lfs.github.com/
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.md
  summary: An open source Git extension for versioning large files
  dev_url: https://github.com/git-lfs/git-lfs
  doc_url: https://github.com/git-lfs/git-lfs/tree/main/docs

extra:
  recipe-maintainers:
    - dfroger
    - willirath
    - dbast
