travis:
  secure:
    BINSTAR_TOKEN: WRhkPOOBqs7gXjBqk/c5zErMZf7vNV1s4yfXVjavbspv4+hTEEe4stk9DPFlCBMPVf9fEj2/dm3XW5tgEoP9ibGvHPXS0WIOfz4cXzE/mrV5idz+Vlg5rUpJIFcVPJK1OyeJ2+o4/TIzhjnntVAeQL1Li6cxnvdxsh6eE47QW5KaN/agckhMdmzUJMzagHU3ULUNTE0sq50XVXMy9vSyzyEhv50ti+A3p36+6MyNRgfPWyvGUO8RFb+T9GrK4hRZiUU5yxjluJZJuECVtRSFpjz3obM+hKAE+bkx3HHd6Bb+LN5XRkWU+WdEkxjHyYOmcVdjKADIFIlXfzbSCgGZtYi5LwHd1TjzrIVw2/oN/e13BuaY5M6BYgpL4X8zUczjR8Kvual3fIphaHU/ojREMZguthS9usJPC6GUM9c2P5zj3lDYa4eSoXws8Yne+nypoFT9Ap9kM+MG7DhJEZO46hBVTkeSbSZrr6hv6Mud8scKNA6Sidqa7fa0+kJWYq0qrkpBG2vbv2PmtAhugfqDEV5OJtJWfcF7ukyjwKyAs6BXhZ6eWurmxMeMuPstF9ls1iakHbtHURKASokXNEOrzBUNbeF2biZtTQUobfNNTnZw1kkw/w7jP5RNrb+fum+Fq3ZADgZxol0R9u6O5uUFLZbFbK4i980tPw0nqnlxZms=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
