travis:
  secure:
    BINSTAR_TOKEN: ePHTE8BEeRgtRAH6KRzXfIi4CZHMv9lOVruiWLwwC9TTBGnxMTFL3d7sxH4PHc3wTvBZ51dn6viDgni9yDCAJBxujd+Z08eUTxB/p6DwFlrqtRUlzGy/DqGGI27SPrN2IpQ8NjRzqr9dDR7Nuw43YWcWYaMaTDM2z79ZznejFpvuFkpFx+nqEyGDDAPmJ1+OCpey/KxcCf0aYPBkuIJmyI78a0JPtToVhObl/j5WExTZzSA0x5gq0PO/mfbFbbH7+xM3Aqik0UmgqkrFQ3yJhpupeDDNzbmpaaSmQIVkj6Z4DZi5W+9wvQsJUobQsFkMM4ttpdDhJV4q7kr2CNtJ+N8x+PHNbxAafsfBJxH/vowxwFV3HKE5jC/zSQKTOLt4Wvw1MJD5Ei4ASfoCzcN+NCzPdNRGeuPcwc5hURZ7kzG43iT9MOC8NhPfy8Z2HSqCGOfxqmdf4U+ICLgCxCru8G77/AM/cSMSrJQ4ZW414uuap54bxik3yQh55MnVTEZ0ke4xsIW131ZPDQZgRrZzIPux/Eaj1EffAH7U+ffMMf/xWYHFppcHsxGs+DqXlXuXfb5g42YA4lxDaFboP89infQP7RC393vTOnoTimCMDU1WD/yfJQaSP8h2YdyHVlu3r76jtLD1exEAyOyR9TC7Knq693oyTw2IJD9C2yEFMcE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
